services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./src:/var/www/html
    
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      PHP_INI_ERROR_DISPLAY: '1'

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: buyitt
      MYSQL_USER: buyitt_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: buyitt_user
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
 
  php:
    image: php:8.1-apache
    container_name: buyitt-marketplace-php
    restart: always
    volumes:
      - ./php:/var/www/html
    ports:
      - "8082:80"
    depends_on:
      - db

volumes:
  db_data: