
services:
  web:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - ./src:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - db
    environment:
      APP_ENV: local
      APP_DEBUG: '1'
      environment:
      DB_HOST: switchyard.proxy.rlwy.net
      DB_PORT: 54044
      DB_USER: root
      DB_PASS: UcewAgrWmZinRKGAynmdaLeUVxYGSCsJ
      DB_NAME: railway
      PHP_INI_ERROR_DISPLAY: '1'
    restart: always

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: buyitt
      MYSQL_USER: buyitt_user
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - db
    environment:
      PMA_HOST: db
      PMA_USER: buyitt_user
      PMA_PASSWORD: secret
    ports:
      - "8081:80"
    restart: always

volumes:
  db_data: